stages:
  - test
  - build
  - deploy

services:
  - docker:dind

lint-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 whatevr

whatevr-unit-tests-job:
  image: python:3-bullseye
  stage: test
  needs:
    - lint-test-job
  script:
    - cd whatevr
    - pip install -r requirements.txt
    - python -m pytest
  when: manual

build-front-end-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: node:lts-bullseye
  needs:
    - whatevr-unit-tests-job
    - lint-test-job
  variables:
    PUBLIC_URL: https://XanderRubio.gitlab.io/clueless
    REACT_APP_WHATEVR_API_HOST: https://clueless.cirrus.mod3projects.com
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public

whatevr-clueless-service-image:
  stage: build
  image: docker:git
  variables:
    CLUELESS_IMAGE: ${CI_REGISTRY_IMAGE}/whatevr_clueless_image
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
  script:
    - docker build --tag $GITLAB_IMAGE:latest whatevr
    - docker push $GITLAB_IMAGE:latest
  only:
    - main

deploy-whatevr-image:
  stage: deploy
  image: registry.gitlab.com/galvanize-inc/foss/glv-cloud-cli:latest
  script:
    - glv-cloud-cli reset -a ${WHATEVR_API} -t ${CIRRUS_TOKEN}
  when: manual
  only:
    - main
