FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
WORKDIR /deps
COPY requirements.txt requirements.txt
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
RUN python -m pip install -r requirements.txt
WORKDIR /app
CMD /wait && uvicorn main:app --reload --host 0.0.0.0


## This is different from Learn
# FROM python:3.10-bullseye
# RUN python -m pip install --upgrade pip
# WORKDIR /app

# # Copy the top-level files
# COPY requirements.txt requirements.txt
# COPY main.py main.py

# # Copy all of the directories that contain your application
# # code
# COPY subdirectory_1 subdirectory_1
# COPY subdirectory_2 subdirectory_2

# RUN pip install -r requirements.txt
# CMD uvicorn main:app --reload --host 0.0.0.0
